server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /Open-One-Setup.exe {
    add_header Content-Disposition 'attachment; filename="Open-One-Setup.exe"';
    add_header Cache-Control "no-store";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
